# Generated by Django 6.0.4 on 2026-04-15 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "board",
                    models.JSONField(help_text="Stores the 8x8 matrix of the board"),
                ),
                (
                    "current_player",
                    models.JSONField(help_text="The current Player object"),
                ),
                ("players", models.JSONField(help_text="Array of 2 Player instances")),
                (
                    "must_jump_piece",
                    models.JSONField(
                        blank=True,
                        help_text="{row: int, col: int} if multi-jump locked",
                        null=True,
                    ),
                ),
                (
                    "winner",
                    models.IntegerField(
                        blank=True, help_text="ID of the winning player", null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoveEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_dir", models.IntegerField()),
                ("from_pos", models.JSONField(help_text="{row: int, col: int}")),
                ("to_pos", models.JSONField(help_text="{row: int, col: int}")),
                ("is_promoted", models.BooleanField(default=False)),
                ("is_jump", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moves",
                        to="game.game",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
