# Generated by Django 6.0.4 on 2026-04-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_alter_moveentry_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="winner",
            new_name="winner_id",
        ),
        migrations.RemoveField(
            model_name="game",
            name="current_player",
        ),
        migrations.AddField(
            model_name="game",
            name="current_player_id",
            field=models.IntegerField(
                default=1, help_text="The current Player object's id"
            ),
            preserve_default=False,
        ),
    ]
