# Generated by Django 6.0.4 on 2026-04-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_rename_winner_game_winner_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
