# Generated by Django 6.0.4 on 2026-04-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='allowed_moves',
            field=models.JSONField(blank=True, default=list, help_text='Cached valid moves for current player'),
        ),
        migrations.AddField(
            model_name='moveentry',
            name='allowed_moves',
            field=models.JSONField(blank=True, default=list, help_text='Cached next-state valid moves'),
        ),
    ]
