# Generated by Django 6.0.4 on 2026-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_allowed_moves_moveentry_allowed_moves'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ai_player_id',
            field=models.IntegerField(blank=True, help_text='Player id controlled by AI in single-player', null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='single_player',
            field=models.BooleanField(default=False, help_text='True when game is user vs AI'),
        ),
    ]
