# Generated by Django 6.0.4 on 2026-04-25 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_game_ai_player_id_game_single_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='single_player',
        ),
    ]
